# .goreleaser.yaml
version: 2
builds:
  -
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      # - netbsd
      # - openbsd
      # - freebsd
      # - windows
    goarch:
      - amd64
      # - arm
      # - arm64
    # goarm:
    #   - "6"
    #   - "7"
    # ignore:
    #   - goos: netbsd
    #     goarch: arm64
    #   - goos: freebsd
    #     goarm: arm64
    #   - goos: linux
    #     goarch: arm
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  disable: false
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  abbrev: -1

release:
  footer: ""

